apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "fullname" . }}-ir-incluster
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.imageRecognizer.inClusterReplicas }}
  template:
    metadata:
      labels:
        app: facial-recognition
    spec:
      containers:
        - name: facial-recognition
          image: {{ default "rbitia/aci-demo:latest" .Values.imageRecognizer.image }}
          imagePullPolicy: Always
          env:
          - name: IP_JOB_SERVER
            value: {{ .Values.imageRecognizer.webServerIP }}:{{ .Values.imageRecognizer.webServerPort }}
          - name: AZURE_BLOB_ACCOUNT
            value: acidemopictures
      dnsPolicy: ClusterFirst
      # Tolerate the ACI taint to get the scheduler to schedule it.
